@startuml

------------------------------------ Editor ------------------------------------
class Editor {
    - id: String
    - text: List<String> 
    - version: AtomicInteger
    - location: List<ByChar>
    - lastEdit: LocalDateTime
    - lastUser: String
}

abstract class Location {
    - user: User
    - row: int 
    - column: int
    - range: int[]
    - editor: Editor
    +{abstract} getBlockedRange(): int[]
}

class ByChar {
    + getBlockedRange(): int[]
}
  
class ByLine {
    + getBlockedRange(): int[]
}

class ByWord {
    + getBlockedRange(): int[]
}

------------------------------------ knowledgeBase ------------------------------------
class Article {
    - tittle: String
    - content: String 
    - author: User 
    - date: LocalDateTime 
    - comments: List<Comment> 
    - likes: Set<User>
    + addComment(comment: Comment): void
}

class Category {
    - id: String
    - name: String 
    - author: User 
    - articles: List<Article>
    + addArticle(article: Article): void
}

class Comment {
    - author: User 
    - content: String  
    - date: LocalDateTime 
    - likes: Set<User> 
}

class Monitor {
}

abstract class Registration{
    - creationDate: Date
}

class Student {
}

class Teacher {
}

class User {
    - id: String
    - username: String
    - email: String
    - name: String
    - lastName: String
    - password: String
    - active: boolean
    - roles: List<String>
}
package knowledgeBase{
  abstract User <<abstract>>
  interface Editable <<Interface>>
  note left of Comment : Max <b>2</b> levels comments  
  User <|-- Student
  User <|-- Monitor
  User <|-- Professor
  Editable <|-- Monitor
  Editable <|-- Professor
  Category -- "articles" Article
  Category "subCcategory" -- Category
  User "user" -- "comments" Comment
  Comment "partner"--"child" Comment
  Comment "comments"--"partner" Version
  Version "articles"--"authors" Professor
  Article --"actual" Version
  Article --"versions" Version
  Editable -- Version
  }
  package OnlineEditor{
    Language -- Intellisense
    Language -- SyntaxChecker
    Language -- ReservedWords
    Text -- Language
    Editor -- Text
    Editor -- Location
    Location <|-- ByWord
    Location <|-- ByLine
    Location <|-- ByChar
    Location -- User
  }
  package WhiteBoard{
    Circle --|> Figure
    Figure <|-- Square
    Figure <|-- Line
    Figure -- Canvas
    Figure --|> DrawTool
    Eraser --|> DrawTool
    ColorChooser --|> DrawTool
    Pencil --|> DrawTool
  }
@enduml
