@startuml

node Client {
}

node BackEnd {
    BoardAPI -# [whiteBoard] 
    EditorAPI -# [textEditor]
    ArticlesAPI -# [articles]
    UsersAPI -# [login/singup]
}

node FrontEnd {
    node "Session"{
        [WhiteBoard] #--( BoardAPI
        [TextEditor] #--( EditorAPI
    }
    [Articles] #--( ArticlesAPI
    [Login/Singup] #--( UsersAPI
}

database MongoDB{
}

BackEnd #--( Driver
Driver -# MongoDB

FrontEnd #--( UserInterface
UserInterface -# Client

@enduml