@startuml

node Client {
}

node FrontEnd {
    node "Session"{
        [WhiteBoard] --( BoardAPI
        [TextEditor] --( EditorAPI
    }
    [Articles] --( ArticlesAPI
    [Login/Singup] --( UsersAPI
}

node BackEnd {
    BoardAPI - [whiteBoard] 
    EditorAPI - [textEditor]
    ArticlesAPI - [articles]
    UsersAPI - [login/singup]
}

database MongoDB{
}

BackEnd --( Driver
Driver - MongoDB

FrontEnd --( UserInterface
UserInterface - Client

@enduml
