@startuml  
  abstract User <<abstract>>
  interface Editable <<Interface>>
  note left of Comment : Max <b>2</b> levels comments  
  User <|-- Student
  User <|-- Monitor
  User <|-- Professor
  Editable <|-- Monitor
  Editable <|-- Professor
  Category -- "articles" Article
  Category "subCcategory" -- Category
  User "user" -- "comments" Comment
  Comment "partner"--"child" Comment
  Comment "comments"--"partner" Version
  Version "articles"--"authors" Professor
  Article --"actual" Version
  Article --"versions" Version
  Editable -- Version
@enduml